name: Deploy snapshots

on:
  push:
    branches: 
      - jruby-9.2
      - deploy_gha

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Build release artifacts
      run: mvn clean package -Prelease
